In [1]:
import numpy as np
# create an array from a list
a = [1, 2, 3, 4, 5]
b = np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
a = [1, 'hello', 3.14]
b = np.array(a)
print(b)

['1' 'hello' '3.14']


In [9]:
# linspace function: create arrays with evenly spaced values
# syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
a = np.linspace(0, 10, 6, dtype=int)
print(a)
a = np.linspace(0, 10, 5, endpoint=False, dtype=int)
print(a)
a, distance = np.linspace(0, 5, 15, retstep=True, endpoint=False)
print(a)
print(distance)

[ 0  2  4  6  8 10]
[0 2 4 6 8]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667]
0.3333333333333333


In [16]:
# arange function: create arrays with evenly spaced values
# syntax: np.arange(start, stop, step, dtype=None)
a = np.arange(0, 10, 2)
print(a)
b = np.arange(0, 15, 0.5)
print(b)

[0 2 4 6 8]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5]


In [ ]:
# logspace function: create arrays with evenly spaced values on a log scale
# syntax: np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

In [26]:
a = np.logspace(0, 3, 4, base=10, dtype=int)
print(a)
a = np.logspace(1, 10, 10, base=2, dtype=int)
print(a)
a = np.logspace(1, 9, 5, base=3, dtype=int)
print(a)
b = np.linspace(1, 9, 5, dtype=int)
print(b)

[   1   10  100 1000]
[   2    4    8   16   32   64  128  256  512 1024]
[    3    27   243  2187 19683]
[1 3 5 7 9]


In [28]:
a = np.zeros(5, dtype=int)
print(a)
a = np.ones(10, dtype=int)
print(a)

[0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


In [34]:
# Arithmetic operations on arrays: +, -, *, /, //, %, **
# with one condition: the arrays must have the same shape
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[0 0 1 2 5]
[1 2 0 0 0]
[ 1 16 27 16  5]


In [36]:
# Arithmetic operations on arrays with a number: +, -, *, /, //, %, **
a = np.array([1, 2, 3, 4, 5])
b = a + 10
print(b)
print(a - 10)
print(a * 10)
print(a / 10)
print(a // 10)
print(a % 10)
print(a ** 10)

[11 12 13 14 15]
[-9 -8 -7 -6 -5]
[10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]
[0 0 0 0 0]
[1 2 3 4 5]
[      1    1024   59049 1048576 9765625]


In [37]:
# create array of 20 random integers from 10 to 99
a = np.random.randint(10, 100, 20)
print(a)

[21 78 73 21 45 65 68 58 96 62 18 91 64 26 25 49 29 42 54 30]


In [38]:
b = a % 2 == 0
print(b)

[False  True False False False False  True  True  True  True  True False
  True  True False False False  True  True  True]


In [40]:
evens = a[b]
print(evens)
odds = a[a % 2 == 1]
print(odds)

[78 68 58 96 62 18 64 26 42 54 30]
[21 73 21 45 65 91 25 49 29]


In [41]:
# create 20 random numbers from -99 to 99
a = np.random.randint(-99, 100, 20)
# find positive numbers
positives = a[a > 0]
# find negative numbers
negatives = a[a < 0]
print(positives, negatives, sep='\n')

[85 67 61 89 98  6 66 16 23 65 40 59]
[-59 -86 -70 -78 -90 -81 -81 -22]


In [46]:
# Create array of 10 integers from 0 to 20 (exclusive), equally spacing by using linspace
a = np.linspace(0, 20, 10, endpoint=False, dtype=int)
print(a)
# Create array of 10 integers from 0 to 20 (exclusive), equally spacing by using arange
a = np.arange(0, 20, 2, dtype=int)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [50]:
a = np.random.randint(0, 100, 20)
print(a)
evens = a[a % 2 == 0]
odds = a[a % 2 == 1]
evens = np.array(sorted(evens))
odds = np.array(sorted(odds))
print(evens, odds, sep='\n')
a = np.concatenate((evens, odds))
print(a)

[32 41 24 33 59 85 76 55 63 54 36 37 53 59 83  8 47 59 61 84]
[ 8 24 32 36 54 76 84]
[33 37 41 47 53 55 59 59 59 61 63 83 85]
[ 8 24 32 36 54 76 84 33 37 41 47 53 55 59 59 59 61 63 83 85]
