In [1]:
# exercise
import numpy as np

y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.])
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2])

v = (y[1:] - y[:-1]) / (t[1:] - t[:-1])
print(v)

[ 2.65306122  7.25490196 11.8        13.79310345 20.85106383 17.38461538]


In [7]:
a = np.random.randint(-99, 100, 20)
print(a)
positives = a[a > 0]
print(positives)
# convert negatives to 0
# a[a < 0] = 0
# convert negatives to their absolute value
a[a < 0] *= -1
print(a)

[ 82 -56  74 -26 -52 -58 -82 -34 -45  -8 -73 -30  93 -85 -97 -55  58 -70
 -42  39]
[82 74 93 58 39]
[82 56 74 26 52 58 82 34 45  8 73 30 93 85 97 55 58 70 42 39]


In [20]:
names = np.array(['Bob Dylan', '', 'Will Smith', 'Mike Tyson', 'William Cuong', 'Joe Hart', 'Laura Amstrong'])
ages = np.array([24, 18, -29, 20, 90, 250, 26])

In [ ]:
# For any empty name, change it to “John Doe”
names[names==''] = 'John'
print(names)
# For any age less than 0, change it to 0
ages[ages < 0] = 0
# For any age greater than 150, change it to 150
ages[ages > 150] = 150
print(ages)
# Find min, max of age
print('Min age =', min(ages))
print('Max age =', max(ages))
# Find longest name, shortest name
print('Longest name =', max(names, key=len))
print('Shortest name =', min(names, key=len))

In [22]:
a = np.array([np.random.randint(10, 100, 5),
              np.random.randint(10, 100, 5),
              np.random.randint(10, 100, 5),
              np.random.randint(10, 100, 5),
              np.random.randint(10, 100, 5)])
print(a)

[[36 23 86 92 47]
 [91 85 12 39 99]
 [13 38 70 88 57]
 [91 94 39 24 30]
 [81 84 61 89 68]]


In [26]:
print(a[2, 4])
print(a[2])
print(a[:, 2])
print(a[:, 2:])

57
[13 38 70 88 57]
[86 12 70 39 61]
[[86 92 47]
 [12 39 99]
 [70 88 57]
 [39 24 30]
 [61 89 68]]


In [27]:
print(a)

[[36 23 86 92 47]
 [91 85 12 39 99]
 [13 38 70 88 57]
 [91 94 39 24 30]
 [81 84 61 89 68]]


In [29]:
print(a[:3, 1:4])
print(a[1:4, 2:4])

[[23 86 92]
 [85 12 39]
 [38 70 88]]
[[12 39]
 [70 88]
 [39 24]]


In [35]:
ones = np.ones((5, 5), dtype=int)
print(ones)
zeros = np.zeros((2, 6), dtype=int)
print(zeros)
twos = ones * 2
print(twos)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [36]:
ones[1] = 0
print(ones)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# a. Create an 8 × 8 array with ones on all the edges and zeros everywhere else. 
ones = np.ones((8, 8), dtype=int)
ones[1:-1, 1:-1] = 0
print(ones)
# b. Create an 8 × 8 array of integers with a checkerboard pattern of ones and zeros.
checkboard = np.zeros((8, 8), dtype=int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)


In [40]:
# c. Create an 8 x 8 array of random integers (10, 99), make all the numbers not divisible by 3 negative. 
a = np.random.randint(10, 100, (8, 8))
print(a)
a[a % 3 != 0] *= -1
print(a)

[[17 77 33 42 19 68 55 29]
 [54 19 17 35 36 48 37 90]
 [10 52 40 79 54 87 15 80]
 [91 38 89 38 64 48 38 17]
 [83 80 91 91 92 58 81 61]
 [76 13 95 44 35 32 54 72]
 [72 29 68 81 78 32 59 70]
 [64 14 94 94 68 37 16 41]]
[[-17 -77  33  42 -19 -68 -55 -29]
 [ 54 -19 -17 -35  36  48 -37  90]
 [-10 -52 -40 -79  54  87  15 -80]
 [-91 -38 -89 -38 -64  48 -38 -17]
 [-83 -80 -91 -91 -92 -58  81 -61]
 [-76 -13 -95 -44 -35 -32  54  72]
 [ 72 -29 -68  81  78 -32 -59 -70]
 [-64 -14 -94 -94 -68 -37 -16 -41]]


In [42]:
# d. Split the matrix above into 4 submatrices 4x4
# e. Find the size, shape, mean, and standard deviation of the matrices you created in part d
q1 = a[:4, :4]
print(np.size(q1))
print(np.shape(q1))

16
(4, 4)


In [45]:
a2d = np.array([[1, 2, 3, 4]])
b1d = np.array([1, 2, 3, 4])
print(a2d, np.shape(a2d))
print(b1d, np.shape(b1d))

[[1 2 3 4]] (1, 4)
[1 2 3 4] (4,)
