In [ ]:
def greater_len(a, b):
    return len(a) > len(b)

def identity(x):
    return x

In [1]:
def my_sort(items, compare=lambda a, b: a > b):
    n = len(items)
    for i in range(n):
        for j in range(n-1):
            if compare(items[j], items[j+1]):
                items[j], items[j+1] = items[j+1], items[j]

In [ ]:
import numpy as np
numbers = np.random.randint(0, 100, 10)
print(numbers)
my_sort(numbers)
print(numbers)
my_sort(numbers, lambda a, b: a < b)
print(numbers)
my_sort(numbers, lambda a, b: a % 10 > b % 10)
print(numbers)

In [7]:
numbers = np.random.randint(-99, 100, 10)
# sort numbers ascending by absolute value
my_sort(numbers, lambda a, b: abs(a) > abs(b))
print(numbers)
# sort numbers descending by absolute value
my_sort(numbers, lambda a, b: abs(a) < abs(b))
print(numbers)
# sort numbers ascending by the sum of the digits
my_sort(numbers, lambda a, b: abs(a) % 10 + abs(a) // 10 > abs(b) % 10 + abs(b) // 10)
print(numbers)
# sort numbers descending by the sum of the digits
my_sort(numbers, lambda a, b: a % 10 + a // 10 < b % 10 + b // 10)
print(numbers)

[  1 -20 -33  47 -63  72  79 -85  87  94]
[ 94  87 -85  79  72 -63  47 -33 -20   1]
[  1 -20 -33  72 -63  47  94 -85  87  79]
[ 79  87  94  47  72 -33   1 -63 -20 -85]


In [8]:
# Write a function to find the 'most' element in a collection of elements.
def most_superior(items, compare=lambda a, b: a > b):
    n = len(items)
    most = items[0]
    for i in range(n):
        if compare(items[i], most):
            most = items[i]
    return most

In [13]:
print(numbers)
m = most_superior(numbers) # max
print(m)
m = most_superior(numbers, lambda a, b: a < b) # min
print(m)
# Find the number which is closest to 0
m = most_superior(numbers, lambda a, b: abs(a) < abs(b))
print(m)
numbers = np.random.randint(0, 100, 10)
print(numbers)
# Find the number which is closest to 50
m = most_superior(numbers, lambda a, b: abs(a - 50) < abs(b - 50))
print(m)

[52 63 69 51 48 82 96 46 37 93]
96
37
37
[48 23 20 73 32 58 82 11 17 44]
48


In [ ]:
# Filter function syntax: filter(function, iterable)
# For each item in iterable, 
# if function(item) is True, then the item is included in the result.

In [15]:
numbers = np.random.randint(0, 100, 20)
print(numbers)
# filter even numbers
evens = list(filter(lambda x: x % 2 == 0, numbers))
print(evens)
odds = list(filter(lambda x: x % 2 == 1, numbers))
print(odds)

[78 31 72 12 43 36 10 46  9 99 59 19 48 23 62 43 89 15 97 94]
[78, 72, 12, 36, 10, 46, 48, 62, 94]
[31, 43, 9, 99, 59, 19, 23, 43, 89, 15, 97]


In [16]:
s = 0
for n in numbers:
    if n % 2 == 0:
        s += n
print(s)

458


In [17]:
evens = [n for n in numbers if n % 2 == 0]
print(sum(evens))

458


In [18]:
evens = filter(lambda x: x % 2 == 0, numbers)
print(sum(evens))

458


In [20]:
numbers = np.random.randint(-99, 100, 20)
print(numbers)
# Find max of negative numbers
print(max(filter(lambda x: x < 0, numbers)))
# Find min of positive numbers
print(min(filter(lambda x: x > 0, numbers)))

[ 77 -30 -65 -56  99 -78 -16 -43 -57 -45  62   2 -72 -99 -94 -36  -6  67
 -41  59]
-6
2


In [22]:
# Each student has GPA and activity score
students = {'John': (7.5, 90), 'Mary': (8.5, 95), 'Bob': (6.0, 80),
            'Alice': (5.5, 45), 'Peter': (8.0, 70), 'Jane': (9.0, 30)}
# Best student is the one with the GPA > 7.0 and highest activity score
candidates = filter(lambda x: x[1][0] > 7.0, students.items())
best_student = max(candidates, key=lambda x: x[1][1])
print(f'Best student is {best_student[0]}')

# Find the most nerd student (activity score < 50 and highest GPA)
candidates = filter(lambda x: x[1][1] < 50, students.items())
nerd_student = max(candidates, key=lambda x: x[1][0])
print(f'Nerd student is {nerd_student[0]}')

Best student is Mary
Nerd student is Jane


In [24]:
# Map function syntax: map(function, iterable)
# Convert each item in iterable to a new item using function
numbers = np.random.randint(-99, 100, 10)
print(numbers)
# double each number
double_numbers = list(map(lambda x: x * 2, numbers))
print(double_numbers)
# convert negative numbers to positive
positive_numbers = list(map(lambda x: x if x > 0 else -x, numbers))
print(positive_numbers)

[-66 -29 -16  57 -18  67 -48 -81 -13  52]
[-132, -58, -32, 114, -36, 134, -96, -162, -26, 104]
[66, 29, 16, 57, 18, 67, 48, 81, 13, 52]


In [25]:
names = ['John', 'Mary', '', 'Alice', '', 'Jane']
# convert empty names => default name (e.g. 'Unknown')
names = list(map(lambda x: x if x != '' else 'Unknown', names))
print(names)

['John', 'Mary', 'Unknown', 'Alice', 'Unknown', 'Jane']
